Repository hitenSharm/Discord-Meme-and-Music-Bot, pull requests merged in 2021-10, with the labels that each got.

#14 Enhanced the Help command
  commands/help.js
Labels: easy

#49 User now has to be in same channel as bot
  commands/okPlayMusic.js
  utils/boolVC.js
Labels: medium

#51 Skip bug
  botFunctions/musicFunction.js
  commands/okPlayMusic.js
Labels: hard

#53 !obm play
  botFunctions/musicFunction.js
  package-lock.json
  package.json
Labels: medium

#55 updated readme
  README.md
Labels: easy
